// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QruqySP9Kz6e2xNDoqbWn6YJSYee7i8',
    appId: '1:671318724180:web:425e96d3f49aa3a833e7c1',
    messagingSenderId: '671318724180',
    projectId: 'loadcontrolproject',
    authDomain: 'loadcontrolproject.firebaseapp.com',
    storageBucket: 'loadcontrolproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTEWEy8qiKc2FzdT3S1a2HIm3EGnEB8I',
    appId: '1:671318724180:android:f5524545593abf1333e7c1',
    messagingSenderId: '671318724180',
    projectId: 'loadcontrolproject',
    storageBucket: 'loadcontrolproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFRXWxPFvsoIhNFDF7xrfHbIdIXY7du9I',
    appId: '1:671318724180:ios:716fa08936ab447b33e7c1',
    messagingSenderId: '671318724180',
    projectId: 'loadcontrolproject',
    storageBucket: 'loadcontrolproject.firebasestorage.app',
    iosBundleId: 'com.example.loadControlProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFRXWxPFvsoIhNFDF7xrfHbIdIXY7du9I',
    appId: '1:671318724180:ios:716fa08936ab447b33e7c1',
    messagingSenderId: '671318724180',
    projectId: 'loadcontrolproject',
    storageBucket: 'loadcontrolproject.firebasestorage.app',
    iosBundleId: 'com.example.loadControlProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QruqySP9Kz6e2xNDoqbWn6YJSYee7i8',
    appId: '1:671318724180:web:2669b0af66dcec1333e7c1',
    messagingSenderId: '671318724180',
    projectId: 'loadcontrolproject',
    authDomain: 'loadcontrolproject.firebaseapp.com',
    storageBucket: 'loadcontrolproject.firebasestorage.app',
  );
}
